endpoints:
  jmx:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sandman?autoReconnect=true
    username: sandman
    password: sandman
#    persistenceUnitName: sandman
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
